### ISSUE TITLE
Add Documentation on how to use it with Docker Compose

### ISSUE THREAD

**Issue by miskolc** [shufo/docker-phoenix#1]
I've run your image using the command from the README `docker run -d -p 4000:4000 -v $(pwd):/app -w /app shufo/phoenix` and it worked fine. The problem is that when I run it with `docker-compose` it complains that there is no `mix.exs` file in the working directory:

`| ** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available
`

**docker-compose.yml**
```
web:
  build: "."
  environment:
    PORT: 4000
    MIX_ENV: "prod"
    DB_USER: deployer
    DB_PASSWORD: secretpass
  ports:
    - "4000:4000"
  links:
    - "db:db"
  volumes:
    - .:/app
```

There seems to be no equivalent for the `-w` flag in docker-compose. If so then the image should be changed so that it can be used in this scenario too.

**Comment by shufo** [comment]
hi @miskolc.

my project's `docker-compose.yml` may be help you.

```dockerfile
app:
  image: shufo/phoenix:1.4.0-development
  container_name: myproject_app
  hostname: app
  expose:
    - 4000
  ports:
    - "4000:4000"
    - "4001:4001"
  working_dir: /code
  environment:
    - "PORT=4000"
  volumes:
    - ".:/code"
  links:
    - mysql
    - redis
```

`working_dir` config corresponds to the `-w` flag and `volumes` config `./code` corresponds to `-v $(pwd):/code`.

in your docker-compose.yml

add 

```diff
web:
  build: "."
  environment:
    PORT: 4000
    MIX_ENV: "prod"
    DB_USER: deployer
    DB_PASSWORD: random2kx
  ports:
    - "4000:4000"
  links:
    - "db:db"
+ working_dir: /app
  volumes:
    - .:/app
```

will phoenix working correctly.

I'll add the document too! thanks.

**Comment by miskolc** [comment]
It solved the issue with `mix.exs` however it still can't access the postgresql database container. 
I get:
` [error] Postgrex.Protocol (#PID<0.307.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect: host is unreachable - :ehostunreach`

I see you are using mysql, have you ever tried using postgres as the database? I've also noticed `postgresql-client` doesn't seem to be installed by the dockerfile.

**Comment by shufo** [comment]
@miskolc 

how was the your `docker-compose.yml`?

I've also tried postgres in 

**docker-compose.yml**

```yaml
  app:
    ...
   links:
     - postgres

  postgres:
    image: postgres:alpine
    container_name: myproject_postgres
    hostname: postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=postgres"
```

**mix.exs**

```elixir
@applications [...
    :postgrex]

...

defp deps do
  ...
  {:postgrex, ">= 0.0.0"}
end
```

**dev.exs**

```elixir
config :myproject, Myproject.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "root",
  database: "postgres",
  hostname: System.get_env("POSTGRES_HOST") || "postgres",
  pool_size: 10
```

then run the migration command `mix ecto.create && mix ecto.migration` in app container is works fine.
There is no need to install `postgresql-client` binary in phoenix image container.

**Comment by miskolc** [comment]
It worked for me after I copy pasted your Dockerfile in my project root and added this line:
`libssl1.0.0 postgresql-client autoclean `\  
for the `apk --update --no-cache add` command.

> There is no need to install postgresql-client binary in phoenix image container.

I don't see how that is possible since Postgrex( used by Ecto) needs the postgresql-client to access the PostgreSQL server. Have you tried the image with postgres? 
Here's the image I use in my docker-compose file:

```
# database image
db:
  image: "postgres:9.6.2-alpine"
  # ports:
  #   - "5432:5432"
  environment:
    POSTGRES_USER: deployer
    POSTGRES_PASSWORD: secretpass
  volumes_from:
    - dbdata

# database data
dbdata:
  image: "postgres:9.6.2-alpine"
  volumes:
    - /var/lib/postgres
  command: "true"
```

I've also seen **postgresql-client** used in Rails containers as well like [here](https://runnable.com/docker/rails/dockerize-your-ruby-on-rails-application).
